name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: welcome message
        run: |
             echo "my first message"
             ls -l
             cat README.md 
      - name: ascyy lib
        run: cowsay -f dragon "RUn" >> dragon.txt